insert into public.clubs (name) values
  ('Abbeyleix Golf Club'),
  ('Achill Island Golf Club'),
  ('Adare Golf Club'),
  ('Allen Park Golf Centre'),
  ('Ardeer Golf Club'),
  ('Ardglass Golf Club'),
  ('Ardminnan Golf Club'),
  ('Arklow Golf Club'),
  ('Ashbourne Golf Club'),
  ('Ashfield Golf Course'),
  ('Ashford Castle Golf Club'),
  ('Athenry Golf Club'),
  ('Athlone Golf Club'),
  ('Athy Golf Club'),
  ('Aughnacloy Golf Club'),
  ('Balbriggan Golf Club'),
  ('Balcarrick Golf Club'),
  ('Ballaghaderreen Golf Club'),
  ('Ballina Golf Club'),
  ('Ballinamore Golf Club'),
  ('Ballinascorney Golf Club'),
  ('Ballinasloe Golf Club'),
  ('Ballinlough Castle Golf Club'),
  ('Ballinrobe Golf Club'),
  ('Ballybofey & Stranorlar Golf Club'),
  ('Ballybunion Golf Club'),
  ('Ballycastle Golf Club'),
  ('Ballyclare Golf Club'),
  ('Ballyearl Golf Club'),
  ('Ballyhaunis Golf Club'),
  ('Ballyheigue Castle Golf Club'),
  ('Ballykisteen Golf & Country Club'),
  ('Ballyliffin Golf Club'),
  ('Ballymena Golf Club'),
  ('Ballymoney Golf Club'),
  ('Ballyneety Golf Club'),
  ('Ballyreagh Golf Club'),
  ('Balmoral Golf Club'),
  ('Baltinglass Golf Club'),
  ('Banbridge Golf Club'),
  ('Bandon Golf Club'),
  ('Bangor Golf Club'),
  ('Bantry Bay Golf Club'),
  ('Bearna Golf & Country Club'),
  ('Beaufort Golf Resort'),
  ('Beaverstown Golf Club'),
  ('Beech Park Golf Club'),
  ('Belturbet Golf Club'),
  ('Belvoir Park Golf Club'),
  ('Benone Golf Club'),
  ('Berehaven Golf Club'),
  ('Birr Golf Club'),
  ('Black Bush Golf Club'),
  ('Blacklion Golf Club'),
  ('Blackwood Golf Club'),
  ('Blainroe Golf Club'),
  ('Blarney Golf Club'),
  ('Borris Golf Club'),
  ('Boyle Golf Club'),
  ('Bray Golf Club'),
  ('Bright Castle Golf Club'),
  ('Brown Trout Golf Club'),
  ('Buncrana Golf Club'),
  ('Bundoran Golf Club'),
  ('Bushfoot Golf Club'),
  ('Cabra Castle Hotel Golf Club'),
  ('Cahir Park Golf Club'),
  ('Cairndhu Golf Club'),
  ('Callan Golf Club'),
  ('Carlow Golf Club'),
  ('Carnalea Golf Club'),
  ('Carne Golf Links'),
  ('Carrick-on-Shannon Golf Club'),
  ('Carrick-on-Suir Golf Club'),
  ('Carrickfergus Golf Club'),
  ('Carrickmines Golf Club'),
  ('Carton House Golf Club'),
  ('Castle Golf Club'),
  ('Castle Hume Golf Club'),
  ('Castlebar Golf Club'),
  ('Castlecomer Golf Club'),
  ('Castlegregory Golf Club'),
  ('Castleisland Golf Club'),
  ('Castlerea Golf Club'),
  ('Castlerock Golf Club'),
  ('Castletroy Golf Club'),
  ('Castlewarden Golf Club'),
  ('Celbridge Elm Hall Golf Club'),
  ('Charleville Golf Club'),
  ('Cill Dara Golf Club'),
  ('City of Belfast Golf Club'),
  ('City of Derry Golf Club'),
  ('City of Derry Golf Course'),
  ('Clandeboye Golf Club'),
  ('Claremorris Golf Club'),
  ('Cliftonville Golf Club'),
  ('Clonakilty Golf Club'),
  ('Clones Golf Club'),
  ('Clonmel Golf Club'),
  ('Clontarf Golf Club'),
  ('Cloverhill Golf Club'),
  ('Cobh Golf Club'),
  ('Concra Wood Golf & Country Club'),
  ('Connemara Golf Club'),
  ('Connemara Isles Golf Club'),
  ('Coollattin Golf Club'),
  ('Coosheen Golf Club'),
  ('Corballis Golf Club'),
  ('Cork Golf Club'),
  ('Corrstown Golf Club'),
  ('County Armagh Golf Club'),
  ('County Cavan Golf Club'),
  ('County Longford Golf Club'),
  ('County Meath (Trim) Golf Club'),
  ('County Sligo Golf Club'),
  ('County Tipperary Golf & Country Club'),
  ('Courtown Golf Club'),
  ('Craddockstown Golf Club'),
  ('Crossgar Golf Club'),
  ('Cruit Island Golf Club'),
  ('Curragh Golf Club'),
  ('Cushendall Golf Club'),
  ('Deer Park Golf Club'),
  ('Delgany Golf Club'),
  ('Dingle (Ceann Sibeal) Golf Club'),
  ('Djouce Mountain Golf Club'),
  ('Donabate Golf Club'),
  ('Donaghadee Golf Club'),
  ('Donegal Golf Club'),
  ('Doneraile Golf Club'),
  ('Dooks Golf Club'),
  ('Douglas Golf Club'),
  ('Downpatrick Golf Club'),
  ('Dromoland Castle Golf Club'),
  ('Druids Glen Golf Club'),
  ('Dublin Mountain Golf Club'),
  ('Dun Laoghaire Golf Club'),
  ('Dundalk Golf Club'),
  ('Dunfanaghy Golf Club'),
  ('Dungannon Golf Club'),
  ('Dungarvan Golf Club'),
  ('Dunloe Golf Club'),
  ('Dunmore Demesne Golf Club'),
  ('Dunmore East Golf Club'),
  ('Dunmurry Golf Club'),
  ('East Clare Golf Club'),
  ('East Cork Golf Club'),
  ('Edenderry Golf Club'),
  ('Edenmore Golf Club'),
  ('Edmondstown Golf Club'),
  ('Elm Park Golf Club'),
  ('Elmgreen Golf Club'),
  ('Ennis Golf Club'),
  ('Enniscorthy Golf Club'),
  ('Enniscrone Golf Club'),
  ('Enniskillen Golf Club'),
  ('Esker Hills Golf Club'),
  ('Faithlegg Golf Club'),
  ('Fermoy Golf Club'),
  ('Fernhill Golf Club'),
  ('Fintona Golf Club'),
  ('Forest Little Golf Club'),
  ('Fortwilliam Golf Club'),
  ('Fota Island Golf Club'),
  ('Foxrock Golf Club'),
  ('Foyle International Golf Centre'),
  ('Frankfield Golf Club'),
  ('Galgorm Castle Golf Club'),
  ('Galway Bay Golf & Country Club'),
  ('Galway Golf Club'),
  ('Gilnahirk Golf Club'),
  ('Glasson Golf Club'),
  ('Glencullen Golf Club'),
  ('Glengarriff Golf Club'),
  ('Glenlo Abbey Golf Club'),
  ('Gold Coast Golf Club'),
  ('Gort Golf Club'),
  ('Gowran Park Golf Club'),
  ('Gracehill Golf Club'),
  ('Grange Castle Golf Club'),
  ('Grange Golf Club'),
  ('Greenacres Golf Centre'),
  ('Greencastle Golf Club'),
  ('Greenisland Golf Club'),
  ('Greenore Golf Club'),
  ('Greystones Golf Club'),
  ('Gweedore Golf Club'),
  ('Headfort Golf Club'),
  ('Helen''s Bay Golf Club'),
  ('Hermitage Golf Club'),
  ('Highfield Golf Club'),
  ('Hilton Belfast Templepatrick Golf & Country Club'),
  ('Hollywood Lakes Golf Club'),
  ('Holywood Golf Club'),
  ('Howth Golf Club'),
  ('Kanturk Golf Club'),
  ('Kenmare Golf Club'),
  ('Kilcock Golf Club'),
  ('Kilkea Castle Golf Club'),
  ('Kilkee Golf Club'),
  ('Kilkeel Golf Club'),
  ('Kilkenny Golf Club'),
  ('Killarney Golf & Fishing Club'),
  ('Killarney Golf Club'),
  ('Killeen Golf Club'),
  ('Killerig Castle Golf Club'),
  ('Killin Park Golf Club'),
  ('Killiney Golf Club'),
  ('Killorglin Golf Club'),
  ('Killymoon Golf Club'),
  ('Kilmashogue Golf Club'),
  ('Kilrea Golf Club'),
  ('Kilrush Golf Club'),
  ('Kilternan Golf Club'),
  ('Kinsale Golf Club'),
  ('Kirkistown Castle Golf Club'),
  ('Knightsbrook Golf Club'),
  ('Knock Golf Club'),
  ('Lahinch Golf Club'),
  ('Lambeg Golf Club'),
  ('Larne Golf Club'),
  ('Laytown & Bettystown Golf Club'),
  ('Lee Valley Golf & Country Club'),
  ('Leopardstown Golf Club'),
  ('Letterkenny Golf Club'),
  ('Limerick Golf Club'),
  ('Lisburn Golf Club'),
  ('Lismore Golf Club'),
  ('Listowel Golf Club'),
  ('Loughgall Country Park & golf course'),
  ('Loughrea Golf Club'),
  ('Lucan Golf Club'),
  ('Lurgan Golf Club'),
  ('Luttrellstown Castle Golf Club'),
  ('Macroom Golf Club'),
  ('Mahee Island Golf Club'),
  ('Mahon Golf Club'),
  ('Malahide Golf Club'),
  ('Mallow Golf Club'),
  ('Malone Edenderry Course'),
  ('Malone Golf Club'),
  ('Mannan Castle Golf Club'),
  ('Manor Golf Club'),
  ('Massereene Golf Club'),
  ('Milltown Golf Club'),
  ('Mitchelstown Golf Club'),
  ('Moate Golf Club'),
  ('Monkstown Golf Club'),
  ('Mount Juliet Golf & Country Club'),
  ('Mount Temple Golf Club'),
  ('Mount Wolseley Golf Hotel & Country Club'),
  ('Mountain View Golf Club'),
  ('Mountbellew Golf Club'),
  ('Mountrath Golf Club'),
  ('Mourne Golf Club'),
  ('Moyola Park Golf Club'),
  ('Moyvalley Golf Club'),
  ('Mullingar Golf Club'),
  ('Mulranny Golf Club'),
  ('Muskerry Golf Club'),
  ('Naas Golf Club'),
  ('Narin & Portnoo Golf Club'),
  ('Nenagh Golf Club'),
  ('New Ross Golf Club'),
  ('Newbridge Golf Club'),
  ('Newcastle West Golf Club'),
  ('Newlands Golf Club'),
  ('Newtownstewart Golf Club'),
  ('North West Golf Club'),
  ('Nuremore Hotel Golf & Country Club'),
  ('Old Conna Golf Club'),
  ('Old Head of Kinsale Golf Club'),
  ('Omagh Golf Club'),
  ('Ormeau Golf Club'),
  ('Otway Golf Club'),
  ('Oughterard Golf Club'),
  ('Palmerstown House Golf Club'),
  ('Parknasilla Golf Club'),
  ('Portadown Golf Club'),
  ('Portarlington Golf Club'),
  ('Portmarnock Championship Course'),
  ('Portmarnock Hotel & Golf Links'),
  ('Portsalon Golf Club'),
  ('Portstewart Golf Club'),
  ('Portumna Golf Club'),
  ('Powerscourt Golf Club'),
  ('R and R Golf Course'),
  ('Raffeen Creek Golf Club'),
  ('Rathbane Golf Club'),
  ('Rathdowney Golf Club'),
  ('Rathfarnham Golf Club'),
  ('Rathmore Golf Club'),
  ('Rathsallagh Golf Club'),
  ('Redcastle Hotel & Golf Club'),
  ('Ring of Kerry Golf Club'),
  ('Rockmount Golf Club'),
  ('Roe Park Resort'),
  ('Roganstown Hotel & CC Golf Club'),
  ('Rosapenna Golf Club'),
  ('Roscommon Golf Club'),
  ('Roscrea Golf Club'),
  ('Ross Golf Club'),
  ('Rosslare Golf Club'),
  ('Rossmore Golf Club'),
  ('Roundwood Golf Club'),
  ('Royal Belfast Golf Club'),
  ('Royal County Down Golf Club'),
  ('Royal Dublin Golf Club'),
  ('Royal Portrush Golf Club'),
  ('Royal Tara Golf Club'),
  ('Rush Golf Club'),
  ('Scrabo Golf Club'),
  ('Seapoint Golf Links'),
  ('Shandon Park Golf Club'),
  ('Shannon Golf Club'),
  ('Silverwood Golf Centre'),
  ('Skellig Bay Golf Club'),
  ('Skerries Golf Club'),
  ('Skibbereen and West Carbery Golf Club'),
  ('Slieve Russell Golf Club'),
  ('Slievenamon Golf Club'),
  ('South County Golf Club'),
  ('South Meath Golf Club'),
  ('Spa Golf Club'),
  ('Spanish Point Golf Club'),
  ('St Anne''s Golf Club'),
  ('St Helen''s Bay Golf Club'),
  ('St Margaret''s Golf Club'),
  ('St Patricks Links Golf Club'),
  ('Stackstown Golf Club'),
  ('Stepaside Golf Club'),
  ('Strabane Golf Club'),
  ('Strandhill Golf Club'),
  ('Strokestown Golf Club'),
  ('Summerhill Golf Club'),
  ('Sutton Golf Club'),
  ('Swinford Golf Club'),
  ('Swords Open Golf Club'),
  ('Tandragee Golf Club'),
  ('Tara Glen Golf Club'),
  ('Temple Golf Club'),
  ('Templemore Golf Club'),
  ('The European Club Golf Club'),
  ('The Heath Golf Club'),
  ('The Heritage Golf Resort'),
  ('The Island Golf Club'),
  ('The K Club Golf Club'),
  ('Thurles Golf Club'),
  ('Tipperary Golf Club'),
  ('Traad Ponds Golf Club'),
  ('Tralee Golf Club'),
  ('Tramore Golf Club'),
  ('Trump International Golf Links & Hotel Doonbeg'),
  ('Tuam Golf Club'),
  ('Tubbercurry Golf Club'),
  ('Tulfarris Golf Club'),
  ('Tullamore Golf Club'),
  ('Virginia Golf Club'),
  ('Warrenpoint Golf Club'),
  ('Waterford Castle Golf Club'),
  ('Waterford Golf Club'),
  ('Waterville Golf Links'),
  ('West Waterford Golf Club'),
  ('Westmanstown Golf Club'),
  ('Westport Golf Club'),
  ('Wexford Golf Club'),
  ('Whitehead Golf Club'),
  ('Wicklow Golf Club'),
  ('Williamstown Golf Club'),
  ('Woodbrook Golf Club'),
  ('Woodenbridge Golf Club'),
  ('Woodstock Golf & Country Club'),
  ('Youghal Golf Club')
on conflict (name) do nothing;
