-- Second half of the local/CI Postgres bootstrap — see
-- setup-local-db-part1.sql for the full explanation of why this exists.
--
-- Run this AFTER 0003_marketplace.sql and BEFORE 0004_tee_time_browse_and_
-- interests.sql: `tee_time_invites` and `profiles.gui_membership_number` were
-- created directly against the live Supabase project outside any committed
-- migration (see claude/admin-architecture-review.md's migration-drift note,
-- and 0032_offers_reconcile.sql for the same failure mode with `offers`), so
-- 0004 — which ALTERs `tee_time_invites` — has no committed migration that
-- creates it first. This is local-test-only scaffolding matching the live
-- table's shape, not a real migration; if `tee_time_invites` is ever
-- reconciled into a proper numbered migration the way 0032 did for `offers`,
-- this file should be deleted. Idempotent: safe to re-run.

create table if not exists public.tee_time_invites (
  id bigint generated by default as identity primary key,
  member_id uuid not null references public.profiles (id) on delete cascade,
  club_name text not null,
  play_date date not null,
  time_from time,
  time_to time,
  exact_tee_time time,
  spaces_available smallint not null check (spaces_available >= 1 and spaces_available <= 3),
  has_tee_time_booked boolean not null default false,
  handicap_limit numeric,
  notes text,
  status text not null default 'open' check (status in ('open', 'full', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

alter table public.tee_time_invites enable row level security;

drop policy if exists "Create own invites" on public.tee_time_invites;
create policy "Create own invites" on public.tee_time_invites
  for insert to public with check (member_id = auth.uid());

drop policy if exists "Delete own invites" on public.tee_time_invites;
create policy "Delete own invites" on public.tee_time_invites
  for delete to public using (member_id = auth.uid());

drop policy if exists "Update own invites" on public.tee_time_invites;
create policy "Update own invites" on public.tee_time_invites
  for update to public using (member_id = auth.uid()) with check (member_id = auth.uid());

drop policy if exists "View open invites or own invites" on public.tee_time_invites;
create policy "View open invites or own invites" on public.tee_time_invites
  for select to public using ((status = 'open') or (member_id = auth.uid()));

alter table public.profiles add column if not exists gui_membership_number text;
