import type { LegalDocument } from "./types";
import { OPERATOR, SUPERVISORY_AUTHORITY, operatorFullDescription } from "./operator";

/**
 * Pinpals Privacy Policy, v1.0 — the Article 13 notice.
 *
 * ============ Read this before editing ============
 *
 * A Privacy Policy is not a liability document and must not be written
 * like one. Article 13 GDPR is a checklist of things a data subject has to
 * be TOLD, in concise, transparent, intelligible and plain language
 * (Art. 12(1)). Every item below is here because Art. 13 or 14 requires
 * it, and vague drafting to keep options open is the specific failure mode
 * the DPC penalises. If a processing activity is not described here,
 * the answer is to describe it — not to broaden a sentence until it
 * technically covers it.
 *
 * Two things this document must stay true to, because they are enforced in
 * the schema and would become misstatements if either changed:
 *
 *  - a member's phone number and date of birth are NOT visible to other
 *    members (0059 and 0074 both put them in owner-read-only tables);
 *  - the newsletter is opt-in, separately from accepting the Terms, and
 *    withdrawing is one toggle (Art. 7(3): as easy to withdraw as to give).
 *
 * The third-party list must be kept accurate. Adding an analytics provider,
 * a chat widget or an email tool without updating section `sharing` — and
 * without revisiting the cookie position in `cookies` — is the most likely
 * way this document quietly becomes wrong.
 *
 * This has not been reviewed by a solicitor or a data protection adviser.
 * It should be, before launch.
 */
export const PRIVACY: LegalDocument = {
  slug: "privacy",
  consentType: "privacy",
  title: "Pinpals Privacy Policy",
  shortTitle: "Privacy Policy",
  version: "1.0",
  effectiveFrom: "2026-09-10",
  summary: "What personal data Pinpals holds about you, why, and what you can do about it.",
  keyPoints: [
    "We hold what you give us: your name, email, and whatever you choose to add — club, county, handicap, photo, phone, date of birth.",
    "Your phone number and date of birth are never shown to other members. Your name, club, county and handicap are, if you fill them in.",
    "We use it to run your account, the marketplace and tee times — not to build a profile of you and not to sell to anyone.",
    "Marketing email is a separate, optional tick. You can switch it off any time, in one click, and we'll never bundle it into agreeing to the Terms.",
    "Stripe, Supabase, Vercel and our email provider process data for us. Stripe handles card details — we never see them.",
    "You can see, correct, export or delete your data, and you can complain to the Data Protection Commission.",
  ],
  sections: [
    {
      id: "controller",
      heading: "1. Who is responsible for your data",
      blocks: [
        {
          kind: "p",
          text: `The data controller for the personal data described here is ${operatorFullDescription()}.`,
        },
        {
          kind: "p",
          text: `For anything to do with your personal data — a question, a correction, a copy, a deletion — write to ${OPERATOR.dataProtectionContact}. We aim to reply within a few days, and we must reply within one month.`,
        },
        {
          kind: "p",
          text: "We are not required to appoint a Data Protection Officer, and we have not appointed one. The address above reaches the people who actually run Pinpals.",
        },
      ],
    },
    {
      id: "what-we-collect",
      heading: "2. What we collect",
      blocks: [
        { kind: "p", text: "Everything below either comes from you or is generated by your use of the site. We do not buy personal data, and we do not collect it about you from anywhere else." },
        {
          kind: "p",
          text: "When you sign up, we need: your first and last name, your email address, a password (stored only as a cryptographic hash — we cannot read it), and your confirmation that you are 18 or over.",
        },
        {
          kind: "p",
          text: "Optionally, at sign-up or later: your mobile number, and how you heard about us.",
        },
        {
          kind: "p",
          text: "Optionally, on your profile: your home club, country and county, your handicap index, a short bio, a profile photograph, your golfing union membership number, and your date of birth.",
        },
        {
          kind: "p",
          text: "As you use the site: your listings and the photographs on them, your offers and bids, your orders, your messages to other members, your reviews, your tee-time availability and the invitations you accept, your notification settings, reports you make about other members, and support cases you open.",
        },
        {
          kind: "p",
          text: "Automatically: a record of which version of each of our legal documents you accepted and when, together with the IP address and browser identifier used at the time; sign-in and security events; and basic technical logs kept by our hosting providers.",
        },
        {
          kind: "p",
          text: "If you sell: the identity and bank details Stripe requires to pay you. These go to Stripe, not to us — we see only that your account is verified and the amounts moving through it.",
        },
        {
          kind: "note",
          text: "We do not ask for, and you should not post, special category data — anything revealing health, ethnicity, religion, political opinions, trade union membership, sexual orientation, or biometric or genetic data. Please do not put any of it in a bio, a listing or a message.",
        },
      ],
    },
    {
      id: "visibility",
      heading: "3. What other members can see",
      blocks: [
        {
          kind: "p",
          text: "Visible to other signed-in members: your name, profile photograph, home club, country, county, bio, and your listings, reviews and tee-time posts. Your handicap is visible only if you switch it on. Your age is shown only as a wide band (for example \"35–44\"), and only if you switch that on separately.",
        },
        {
          kind: "note",
          text: "Never visible to other members: your email address, your phone number, your date of birth itself, your golfing union membership number, your payment details, your notification settings, and your consent records. These are held in a way that other members' accounts cannot read, not merely hidden by the design of a page.",
        },
        {
          kind: "p",
          text: "Messages you send another member are visible to that member, and to our staff where they need to look into a report, a dispute or a support case.",
        },
        {
          kind: "p",
          text: "Some pages are visible to anyone on the internet, including our course directory and public marketplace listings. Your profile and the member directory are not — they require an account.",
        },
      ],
    },
    {
      id: "why",
      heading: "4. Why we use it, and our legal basis",
      blocks: [
        {
          kind: "p",
          text: "To create and run your account, show your profile, and let you use tee times and the marketplace — because it is necessary to perform our contract with you (Article 6(1)(b) GDPR).",
        },
        {
          kind: "p",
          text: "To take payments, pay sellers, handle refunds, and meet the record-keeping that goes with it — necessary to perform that contract, and in part a legal obligation (Article 6(1)(c)).",
        },
        {
          kind: "p",
          text: "To send you transactional email you cannot switch off — confirming an order, a payment, a refund, a dispute or a password reset — necessary to perform the contract. These are not marketing, and we keep them to what you need to know.",
        },
        {
          kind: "p",
          text: "To keep the platform safe: investigating reports, preventing fraud and abuse, enforcing the Terms, and keeping records of what happened — our legitimate interest in a platform members can trust and in protecting them and ourselves (Article 6(1)(f)). We have weighed this against your interests, and it is limited to what that purpose needs.",
        },
        {
          kind: "p",
          text: "To understand which parts of the site are used and to fix what is broken — the same legitimate interest, using aggregated information rather than anything that singles you out.",
        },
        {
          kind: "p",
          text: "To send you the weekly Pinpals golf digest — only with your consent (Article 6(1)(a)), given by a separate tick you can withdraw at any time.",
        },
        {
          kind: "p",
          text: "To publish your age band, and to publish your handicap — only with your consent, given by the switches on your profile and withdrawn by turning them off.",
        },
        {
          kind: "p",
          text: "To keep proof of what you agreed to and when — a legal obligation, since Article 7(1) requires us to be able to demonstrate your consent.",
        },
        {
          kind: "p",
          text: "We do not use your personal data to make automated decisions that produce legal effects for you, and we do not carry out profiling in that sense.",
        },
      ],
    },
    {
      id: "sharing",
      heading: "5. Who else touches it",
      blocks: [
        {
          kind: "p",
          text: "We do not sell your personal data, and we do not share it with anyone for their own marketing. We use the following providers, each under a contract that limits them to acting on our instructions:",
        },
        {
          kind: "ul",
          items: [
            "Supabase — the database and authentication behind the site, where your account and content are stored.",
            "Vercel — hosting for the website itself, which also keeps short-lived technical request logs.",
            "Stripe — payment processing and seller payouts. Stripe handles card and bank details directly and acts as its own controller for parts of that, under its own privacy policy.",
            "Our email provider — sending account, notification and (if you have opted in) newsletter email.",
          ],
        },
        {
          kind: "p",
          text: "The golf news on Pinpals is produced with the help of AI tools working from published golf sources. No member's personal data is sent to those tools.",
        },
        {
          kind: "p",
          text: "We will disclose personal data where the law requires it, to establish or defend a legal claim, or to protect someone's safety. If Pinpals is ever sold or transferred, member data would move with it, and we would tell you beforehand.",
        },
        {
          kind: "p",
          text: "Some of these providers process data outside the European Economic Area, including in the United States. Where they do, the transfer relies on the European Commission's Standard Contractual Clauses or an adequacy decision, together with the provider's own safeguards. You can ask us for details of the safeguards that apply.",
        },
      ],
    },
    {
      id: "retention",
      heading: "6. How long we keep it",
      blocks: [
        {
          kind: "p",
          text: "Your account and profile: for as long as your account is open. When you close it, we delete or anonymise your profile, listings, messages and tee-time history, except where something below requires us to keep a record.",
        },
        {
          kind: "p",
          text: "Orders, payments, refunds and commission records: six years from the end of the tax year they fall in, because tax and accounting law requires it and because a claim can be brought within six years.",
        },
        {
          kind: "p",
          text: "Reports about members, and the outcome of a dispute or a suspension: up to six years, so that a pattern of behaviour is not erased by opening a new account.",
        },
        {
          kind: "p",
          text: "Records of which legal documents you accepted: for as long as your account exists. They are deleted with it.",
        },
        {
          kind: "p",
          text: "Newsletter consent and unsubscribe records: for as long as you are subscribed, and then a minimal record of the unsubscribe so that we do not email you again by mistake.",
        },
        {
          kind: "p",
          text: "Technical logs kept by our hosting providers: short-lived, typically days to a few weeks, under those providers' own retention settings.",
        },
      ],
    },
    {
      id: "security",
      heading: "7. How we protect it",
      blocks: [
        {
          kind: "p",
          text: "Traffic to the site is encrypted in transit. Passwords are stored only as hashes. The database enforces access rules row by row, so that one member's account cannot read another member's private data even if the website itself had a bug. Card details never reach our systems.",
        },
        {
          kind: "p",
          text: "Access by our staff is limited to the people who need it, and administrative actions are recorded in an audit log.",
        },
        {
          kind: "p",
          text: "No system is perfectly secure. If a breach happens that is likely to put your rights and freedoms at risk, we will tell you, and we will notify the Data Protection Commission within 72 hours as the law requires.",
        },
      ],
    },
    {
      id: "rights",
      heading: "8. Your rights",
      blocks: [
        { kind: "p", text: "You have the right to:" },
        {
          kind: "ul",
          items: [
            "ask what personal data we hold about you, and get a copy of it;",
            "have inaccurate data corrected — most of it you can edit yourself on your profile;",
            "have your data deleted, where we have no overriding reason to keep it (section 6 sets out where we do);",
            "ask us to restrict how we use it while a question about it is resolved;",
            "receive the data you gave us in a machine-readable format, and have it sent to another provider where that is technically possible;",
            "object to our using your data on the basis of legitimate interests, including for any profiling based on it — tell us why, and we will stop unless we have compelling grounds that override your objection;",
            "object at any time, with no reason needed, to your data being used for direct marketing — and we will stop immediately;",
            "withdraw any consent you have given, without affecting what we did lawfully before you withdrew it.",
          ],
        },
        {
          kind: "p",
          text: `To exercise any of these, write to ${OPERATOR.dataProtectionContact}. We will not charge you, and we will not make you give a reason. We may need to check who you are before we act.`,
        },
        {
          kind: "note",
          text: `If you are unhappy with how we have handled your data you can complain to the ${SUPERVISORY_AUTHORITY.name}, ${SUPERVISORY_AUTHORITY.address} — ${SUPERVISORY_AUTHORITY.website}. You can do that whether or not you have raised it with us first, though we would like the chance to put it right.`,
        },
      ],
    },
    {
      id: "marketing",
      heading: "9. Email and marketing",
      blocks: [
        {
          kind: "p",
          text: "Transactional email — order confirmations, payment and refund notices, password resets, security alerts — is part of running your account and cannot be switched off while your account is open.",
        },
        {
          kind: "p",
          text: "Notification email about activity on the site — messages, offers, auctions, reviews, tee times — is on by default and can be turned off category by category in your notification settings.",
        },
        {
          kind: "p",
          text: "The weekly Pinpals golf digest is marketing. We only send it if you asked for it, by a separate tick at sign-up or a switch in your dashboard that is never pre-ticked and never bundled with accepting the Terms. Every issue carries a one-click unsubscribe, and you can turn it off in your dashboard just as easily as you turned it on.",
        },
      ],
    },
    {
      id: "cookies",
      heading: "10. Cookies",
      blocks: [
        {
          kind: "p",
          text: "Pinpals sets only the cookies it needs to work: a cookie that keeps you signed in, and cookies Stripe sets to process a payment and prevent fraud. These are strictly necessary for a service you asked for, so we do not ask for consent to them — but you should know they are there.",
        },
        {
          kind: "p",
          text: "We do not use advertising cookies, tracking pixels or third-party analytics that follow you across other websites. If that ever changes we will ask for your consent before setting them, and this section will say so first.",
        },
      ],
    },
    {
      id: "children",
      heading: "11. Children",
      blocks: [
        {
          kind: "p",
          text: "Pinpals is for adults. You must be 18 or over to hold an account, and we ask you to confirm it when you sign up. We do not knowingly collect data about anyone under 18, and if we find that we have, we will delete the account and the data. If you believe a child has signed up, please tell us.",
        },
      ],
    },
    {
      id: "changes",
      heading: "12. Changes to this policy",
      blocks: [
        {
          kind: "p",
          text: "Every version of this policy has a number and a date, and the version you were shown is recorded with your account. If we change it in a way that matters to you, we will tell you and, where the law requires it, ask you again before relying on the change.",
        },
      ],
    },
  ],
};
